services:
  - type: web
    name: evcharge-x
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/users
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        value: evcharge_db